----CASO2 FORMA 1

SET SERVEROUTPUT ON;
VAR B_ANNIO NUMBER
EXEC :B_ANNIO := TO_CHAR(SYSDATE,'MMYYYY');

VAR B_RUN NUMBER
EXEC :B_RUN := 12648200;

--ESTADOS CIVILES
VAR B_EST1 VARCHAR2 
EXEC :B_EST1:='CASADO'

VAR B_EST2 VARCHAR2 
EXEC :B_EST2:='ACUERDO DE UNION CIVIL'

VAR B_EST3 VARCHAR2 
EXEC :B_EST3:='DIVORCIADO'

VAR B_EST4 VARCHAR2 
EXEC :B_EST4:='SOLTERO'

VAR B_EST5 VARCHAR2 
EXEC :B_EST5:='VIUDO'

VAR B_EST6 VARCHAR2 
EXEC :B_EST6:='SEPARADO'





DECLARE

  V_NUMRUN_EMP USUARIO_CLAVE.NUMRUN_EMP%TYPE;
  V_DVRUN_EMP USUARIO_CLAVE.DVRUN_EMP%TYPE;
  V_NOMBRE_EMPLEADO USUARIO_CLAVE.NOMBRE_EMPLEADO%TYPE;
  V_NOMBRE_USUARIO USUARIO_CLAVE.NOMBRE_USUARIO%TYPE;
  V_CLAVE_USUARIO USUARIO_CLAVE.CLAVE_USUARIO%TYPE;
  V_ANNOS_CONTRATO NUMBER;
  V_SUELDO_BASE EMPLEADO.SUELDO_BASE%TYPE;
  V_PRIMER_NOMBRE VARCHAR2(25);
  V_ESTADO_CIVIL ESTADO_CIVIL.NOMBRE_ESTADO_CIVIL%TYPE;
  V_COMUNA COMUNA.NOMBRE_COMUNA%TYPE;
  V_APPATERNO_LETRAS VARCHAR2(2);
  V_APPATERNO_EMP EMPLEADO.APPATERNO_EMP%TYPE;
  V_FECHA_NAC EMPLEADO.FECHA_NAC%TYPE;



BEGIN

   

  SELECT
    NUMRUN_EMP,DVRUN_EMP,
    PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP,
    SUELDO_BASE,
    ROUND(MONTHS_BETWEEN(SYSDATE, FECHA_CONTRATO)/12),
    EC.NOMBRE_ESTADO_CIVIL,
    C.NOMBRE_COMUNA,
    APPATERNO_EMP,
    FECHA_NAC
  INTO 
    V_NUMRUN_EMP, 
    V_DVRUN_EMP, 
    V_NOMBRE_EMPLEADO, 
    V_SUELDO_BASE, 
    V_ANNOS_CONTRATO, 
    V_ESTADO_CIVIL, 
    V_COMUNA,
    V_APPATERNO_EMP,
    V_FECHA_NAC
  FROM EMPLEADO E 
  INNER JOIN COMUNA C ON (E.ID_COMUNA = C.ID_COMUNA)
  INNER JOIN ESTADO_CIVIL EC ON (E.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL)
  WHERE NUMRUN_EMP = :B_RUN;

 
  V_PRIMER_NOMBRE := SUBSTR(V_NOMBRE_EMPLEADO, 1, INSTR(V_NOMBRE_EMPLEADO, ' ') - 1);--extrae una subcadena de la cadena V_NOMBRE_EMPLEADO desde el primer carácter hasta el carácter antes del primer espacio en blanco

   
  --AÑOS CONTRATADOS

  IF V_ANNOS_CONTRATO < 10 THEN

    V_NOMBRE_USUARIO := SUBSTR(V_NOMBRE_EMPLEADO,0,3)||LENGTH(V_PRIMER_NOMBRE)||'*'||SUBSTR(V_SUELDO_BASE,-1)||V_DVRUN_EMP||V_ANNOS_CONTRATO||'X';

  ELSE

    V_NOMBRE_USUARIO := SUBSTR(V_NOMBRE_EMPLEADO,0,3)||LENGTH(V_PRIMER_NOMBRE)||'*'||SUBSTR(V_SUELDO_BASE,-1)||V_DVRUN_EMP||V_ANNOS_CONTRATO;

  END IF;

   

  --ESTADOS CIVILES

  IF V_ESTADO_CIVIL = :B_EST1 OR V_ESTADO_CIVIL = :B_EST2 THEN
    V_APPATERNO_LETRAS := LOWER(SUBSTR(V_APPATERNO_EMP,1,2));
     
  ELSIF V_ESTADO_CIVIL = :B_EST3 OR V_ESTADO_CIVIL = :B_EST4 THEN
    V_APPATERNO_LETRAS := LOWER(SUBSTR(V_APPATERNO_EMP,1,1)||SUBSTR(V_APPATERNO_EMP,-1,1));
   
  ELSIF V_ESTADO_CIVIL = :B_EST5 THEN
    V_APPATERNO_LETRAS := LOWER(SUBSTR(V_APPATERNO_EMP,-3,2));

     
  ELSIF V_ESTADO_CIVIL = :B_EST6 THEN
    V_APPATERNO_LETRAS := LOWER(SUBSTR(V_APPATERNO_EMP,-2,2));

  ELSE

     V_APPATERNO_LETRAS := NULL;

     

  END IF;

   

  V_CLAVE_USUARIO := SUBSTR(V_NUMRUN_EMP,3,1) || EXTRACT(YEAR FROM V_FECHA_NAC) + 2 || 
            SUBSTR(V_SUELDO_BASE, -3, 3) - 1 || V_APPATERNO_LETRAS ||
            :B_ANNIO || SUBSTR(V_COMUNA,1,1);
   

  DBMS_OUTPUT.PUT_LINE('MES Y AÑO: ' || :B_ANNIO);
  DBMS_OUTPUT.PUT_LINE('RUT EMPLEADO: ' || V_NUMRUN_EMP ||'-'||V_DVRUN_EMP);
  DBMS_OUTPUT.PUT_LINE('NOMBRE EMPLEADO: ' || V_NOMBRE_EMPLEADO);
  DBMS_OUTPUT.PUT_LINE('NOMBRE USUARIO: ' || V_NOMBRE_USUARIO);
  DBMS_OUTPUT.PUT_LINE('CLAVE USUARIO: ' || V_CLAVE_USUARIO);

INSERT INTO USUARIO_CLAVE (MES_ANNO,NUMRUN_EMP,DVRUN_EMP,NOMBRE_EMPLEADO,
NOMBRE_USUARIO,CLAVE_USUARIO)VALUES(:B_ANNIO,V_NUMRUN_EMP,V_DVRUN_EMP,
V_NOMBRE_EMPLEADO,V_NOMBRE_USUARIO,V_CLAVE_USUARIO);
COMMIT;

END;


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



--CASO2 FORMA 2
SET SERVEROUTPUT ON;

VAR B_RUT NUMBER;
EXEC :B_RUT := 12642309;

DECLARE
V_MES_ANNO USUARIO_CLAVE.MES_ANNO%TYPE;
V_NUMRUN_EMP USUARIO_CLAVE.NUMRUN_EMP%TYPE;
V_DVRUN_EMP USUARIO_CLAVE.DVRUN_EMP%TYPE;
V_NOMBRE_EMPLEADO USUARIO_CLAVE.NOMBRE_EMPLEADO%TYPE;
V_NOMBRE_USUARIO USUARIO_CLAVE.NOMBRE_USUARIO%TYPE;
V_CLAVE_USUARIO USUARIO_CLAVE.CLAVE_USUARIO%TYPE;

BEGIN
    
    SELECT
    TO_CHAR(SYSDATE, 'MMYYYY'),
    DVRUN_EMP,
    PNOMBRE_EMP ||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP
    INTO V_MES_ANNO, V_DVRUN_EMP, V_NOMBRE_EMPLEADO
    FROM EMPLEADO
    WHERE NUMRUN_EMP = :B_RUT;
    
   
   SELECT 
   SUBSTR(PNOMBRE_EMP,1,3) || LENGTH(PNOMBRE_EMP) || '*' || SUBSTR(SUELDO_BASE,-1,1) || V_DVRUN_EMP || ROUND (MONTHS_BETWEEN(SYSDATE, FECHA_CONTRATO)/12) ||
   CASE 
   WHEN ROUND (MONTHS_BETWEEN(SYSDATE, FECHA_CONTRATO)/12) < 10 THEN 'X'
   END
   INTO V_NOMBRE_USUARIO
   FROM EMPLEADO
   WHERE NUMRUN_EMP = :B_RUT ; --AGREGAR LO DE MENOS DE 10 AÑOS
   
    SELECT
   SUBSTR(E.NUMRUN_EMP,3,1) || EXTRACT(YEAR FROM E.FECHA_NAC)+2 || SUBSTR(E.SUELDO_BASE, -3, 3)-1 || 
   LOWER(CASE
    WHEN E.ID_ESTADO_CIVIL = 10 OR E.ID_ESTADO_CIVIL = 60 THEN SUBSTR(E.APPATERNO_EMP, 1,2)
    WHEN E.ID_ESTADO_CIVIL = 20 OR E.ID_ESTADO_CIVIL = 30 THEN SUBSTR(E.APPATERNO_EMP, 1,1)||SUBSTR(E.APPATERNO_EMP, -1,1)
    WHEN E.ID_ESTADO_CIVIL = 40 THEN SUBSTR(E.APPATERNO_EMP, -3,2)
    WHEN E.ID_ESTADO_CIVIL = 50 THEN SUBSTR(E.APPATERNO_EMP, -1,2)
   END) ||
   EXTRACT(MONTH FROM SYSDATE) || EXTRACT(YEAR FROM SYSDATE) ||
   SUBSTR(C.NOMBRE_COMUNA,1,1)
   INTO V_CLAVE_USUARIO
   FROM EMPLEADO E
   INNER JOIN COMUNA C ON C.ID_COMUNA = E.ID_COMUNA
   WHERE NUMRUN_EMP = :B_RUT; 
    
    DBMS_OUTPUT.PUT_LINE(V_MES_ANNO);
    DBMS_OUTPUT.PUT_LINE(V_NOMBRE_EMPLEADO);
    DBMS_OUTPUT.PUT_LINE(:b_rut);
    DBMS_OUTPUT.PUT_LINE(V_DVRUN_EMP);
    DBMS_OUTPUT.PUT_LINE(V_NOMBRE_USUARIO);
    DBMS_OUTPUT.PUT_LINE(V_CLAVE_USUARIO);
    
    INSERT INTO USUARIO_CLAVE (MES_ANNO,NUMRUN_EMP,DVRUN_EMP,NOMBRE_EMPLEADO,
NOMBRE_USUARIO,CLAVE_USUARIO)VALUES(V_MES_ANNO,V_NUMRUN_EMP,V_DVRUN_EMP,
V_NOMBRE_EMPLEADO,V_NOMBRE_USUARIO,V_CLAVE_USUARIO);
COMMIT;
END;
